[package]
name = "kvs"
version = "0.1.0"
authors = ["ShuLiang <shuliang@live.cn>"]
description = "A key-value store"
edition = "2018"

[dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
clap = "2.33.0"
