[package]
name = "slog_demo"
version = "0.1.0"
authors = ["ShuLiang <shuliang@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
slog = "2.7.0"
slog-async = "2.6.0"
slog-json = "2.3.0"
