[package]
name = "todomvc"
version = "0.1.0"
authors = ["ShuLiang <shuliang@live.cn>"]
edition = "2018"

[dependencies]
strum = "0.20"
strum_macros = "0.20"
serde = { version = "1.0", features = ["derive"] }
# yew = "0.17.4"
yew = { git = "https://github.com/yewstack/yew", rev = "2c60d59" }
